apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tas-mcp-servers

resources:
  - namespace.yaml
  - crawl4ai
  - napkin-mcp
  - napkin-operator
  - napkin-federation-init.yaml

commonLabels:
  project: tas
  tier: mcp-servers
