apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tas-mcp-servers

resources:
  - namespace.yaml
  - crawl4ai

commonLabels:
  project: tas
  tier: mcp-servers
