---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dbhub-tas-io-v1alpha1-database
  failurePolicy: Fail
  name: mdatabase-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dbhub.tas.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dbhub-tas-io-v1alpha1-dbhubinstance
  failurePolicy: Fail
  name: mdbhubinstance-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dbhub.tas.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbhubinstances
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dbhub-tas-io-v1alpha1-database
  failurePolicy: Fail
  name: vdatabase-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dbhub.tas.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dbhub-tas-io-v1alpha1-dbhubinstance
  failurePolicy: Fail
  name: vdbhubinstance-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dbhub.tas.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbhubinstances
  sideEffects: None
