apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: napkin-mcp

namespace: tas-mcp-servers

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml

commonLabels:
  project: tas
  tier: mcp-servers
  service: napkin-mcp
