# This rule is not used by the project dbhub-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dbhub.tas.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dbhub-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbhubinstance-viewer-role
rules:
- apiGroups:
  - dbhub.tas.io
  resources:
  - dbhubinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbhub.tas.io
  resources:
  - dbhubinstances/status
  verbs:
  - get
